//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CultureAppModel", "FK__Conversat__Partn__0CBAE877", "CultureFiveDimension", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(citPOINT.CultureApp.Data.Web.CultureFiveDimension), "ConversationCulture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.CultureApp.Data.Web.ConversationCulture), true)]
[assembly: EdmRelationshipAttribute("CultureAppModel", "FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(citPOINT.CultureApp.Data.Web.CultureFiveDimension), "DomainCultureMapping", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.CultureApp.Data.Web.DomainCultureMapping), true)]
[assembly: EdmRelationshipAttribute("CultureAppModel", "FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(citPOINT.CultureApp.Data.Web.CultureFiveDimension), "NegotiationCulture", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(citPOINT.CultureApp.Data.Web.NegotiationCulture), true)]

#endregion

namespace citPOINT.CultureApp.Data.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CultureAppEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CultureAppEntities object using the connection string found in the 'CultureAppEntities' section of the application configuration file.
        /// </summary>
        public CultureAppEntities() : base("name=CultureAppEntities", "CultureAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CultureAppEntities object.
        /// </summary>
        public CultureAppEntities(string connectionString) : base(connectionString, "CultureAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CultureAppEntities object.
        /// </summary>
        public CultureAppEntities(EntityConnection connection) : base(connection, "CultureAppEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ConversationCulture> ConversationCultures
        {
            get
            {
                if ((_ConversationCultures == null))
                {
                    _ConversationCultures = base.CreateObjectSet<ConversationCulture>("ConversationCultures");
                }
                return _ConversationCultures;
            }
        }
        private ObjectSet<ConversationCulture> _ConversationCultures;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CultureFiveDimension> CultureFiveDimensions
        {
            get
            {
                if ((_CultureFiveDimensions == null))
                {
                    _CultureFiveDimensions = base.CreateObjectSet<CultureFiveDimension>("CultureFiveDimensions");
                }
                return _CultureFiveDimensions;
            }
        }
        private ObjectSet<CultureFiveDimension> _CultureFiveDimensions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DomainCultureMapping> DomainCultureMappings
        {
            get
            {
                if ((_DomainCultureMappings == null))
                {
                    _DomainCultureMappings = base.CreateObjectSet<DomainCultureMapping>("DomainCultureMappings");
                }
                return _DomainCultureMappings;
            }
        }
        private ObjectSet<DomainCultureMapping> _DomainCultureMappings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<NegotiationCulture> NegotiationCultures
        {
            get
            {
                if ((_NegotiationCultures == null))
                {
                    _NegotiationCultures = base.CreateObjectSet<NegotiationCulture>("NegotiationCultures");
                }
                return _NegotiationCultures;
            }
        }
        private ObjectSet<NegotiationCulture> _NegotiationCultures;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ConversationCultures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToConversationCultures(ConversationCulture conversationCulture)
        {
            base.AddObject("ConversationCultures", conversationCulture);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CultureFiveDimensions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCultureFiveDimensions(CultureFiveDimension cultureFiveDimension)
        {
            base.AddObject("CultureFiveDimensions", cultureFiveDimension);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DomainCultureMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDomainCultureMappings(DomainCultureMapping domainCultureMapping)
        {
            base.AddObject("DomainCultureMappings", domainCultureMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the NegotiationCultures EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNegotiationCultures(NegotiationCulture negotiationCulture)
        {
            base.AddObject("NegotiationCultures", negotiationCulture);
        }

        #endregion
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="negotiationCultureID">No Metadata Documentation available.</param>
        public ObjectResult<NegotiationCulture> GetNegotiationCultureByNegID(Nullable<global::System.Guid> negotiationCultureID)
        {
            ObjectParameter negotiationCultureIDParameter;
            if (negotiationCultureID.HasValue)
            {
                negotiationCultureIDParameter = new ObjectParameter("NegotiationCultureID", negotiationCultureID);
            }
            else
            {
                negotiationCultureIDParameter = new ObjectParameter("NegotiationCultureID", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<NegotiationCulture>("GetNegotiationCultureByNegID", negotiationCultureIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="negotiationCultureID">No Metadata Documentation available.</param>
        public ObjectResult<NegotiationCulture> GetNegotiationCultureByNegID(Nullable<global::System.Guid> negotiationCultureID, MergeOption mergeOption)
        {
            ObjectParameter negotiationCultureIDParameter;
            if (negotiationCultureID.HasValue)
            {
                negotiationCultureIDParameter = new ObjectParameter("NegotiationCultureID", negotiationCultureID);
            }
            else
            {
                negotiationCultureIDParameter = new ObjectParameter("NegotiationCultureID", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<NegotiationCulture>("GetNegotiationCultureByNegID", mergeOption, negotiationCultureIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="conversationCultureID">No Metadata Documentation available.</param>
        public ObjectResult<ConversationCulture> GetConversationCultureByConvID(Nullable<global::System.Guid> conversationCultureID)
        {
            ObjectParameter conversationCultureIDParameter;
            if (conversationCultureID.HasValue)
            {
                conversationCultureIDParameter = new ObjectParameter("ConversationCultureID", conversationCultureID);
            }
            else
            {
                conversationCultureIDParameter = new ObjectParameter("ConversationCultureID", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ConversationCulture>("GetConversationCultureByConvID", conversationCultureIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="conversationCultureID">No Metadata Documentation available.</param>
        public ObjectResult<ConversationCulture> GetConversationCultureByConvID(Nullable<global::System.Guid> conversationCultureID, MergeOption mergeOption)
        {
            ObjectParameter conversationCultureIDParameter;
            if (conversationCultureID.HasValue)
            {
                conversationCultureIDParameter = new ObjectParameter("ConversationCultureID", conversationCultureID);
            }
            else
            {
                conversationCultureIDParameter = new ObjectParameter("ConversationCultureID", typeof(global::System.Guid));
            }
    
            return base.ExecuteFunction<ConversationCulture>("GetConversationCultureByConvID", mergeOption, conversationCultureIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="cultureID">No Metadata Documentation available.</param>
        public ObjectResult<CultureFiveDimension> GetFiveDimensionByCultureID(Nullable<global::System.Int32> cultureID)
        {
            ObjectParameter cultureIDParameter;
            if (cultureID.HasValue)
            {
                cultureIDParameter = new ObjectParameter("CultureID", cultureID);
            }
            else
            {
                cultureIDParameter = new ObjectParameter("CultureID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<CultureFiveDimension>("GetFiveDimensionByCultureID", cultureIDParameter);
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="mergeOption"></param>
        /// <param name="cultureID">No Metadata Documentation available.</param>
        public ObjectResult<CultureFiveDimension> GetFiveDimensionByCultureID(Nullable<global::System.Int32> cultureID, MergeOption mergeOption)
        {
            ObjectParameter cultureIDParameter;
            if (cultureID.HasValue)
            {
                cultureIDParameter = new ObjectParameter("CultureID", cultureID);
            }
            else
            {
                cultureIDParameter = new ObjectParameter("CultureID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<CultureFiveDimension>("GetFiveDimensionByCultureID", mergeOption, cultureIDParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CultureAppModel", Name="ConversationCulture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ConversationCulture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ConversationCulture object.
        /// </summary>
        /// <param name="conversationCultureID">Initial value of the ConversationCultureID property.</param>
        public static ConversationCulture CreateConversationCulture(global::System.Guid conversationCultureID)
        {
            ConversationCulture conversationCulture = new ConversationCulture();
            conversationCulture.ConversationCultureID = conversationCultureID;
            return conversationCulture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ConversationCultureID
        {
            get
            {
                return _ConversationCultureID;
            }
            set
            {
                if (_ConversationCultureID != value)
                {
                    OnConversationCultureIDChanging(value);
                    ReportPropertyChanging("ConversationCultureID");
                    _ConversationCultureID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ConversationCultureID");
                    OnConversationCultureIDChanged();
                }
            }
        }
        private global::System.Guid _ConversationCultureID;
        partial void OnConversationCultureIDChanging(global::System.Guid value);
        partial void OnConversationCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> ConversationID
        {
            get
            {
                return _ConversationID;
            }
            set
            {
                OnConversationIDChanging(value);
                ReportPropertyChanging("ConversationID");
                _ConversationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ConversationID");
                OnConversationIDChanged();
            }
        }
        private Nullable<global::System.Guid> _ConversationID;
        partial void OnConversationIDChanging(Nullable<global::System.Guid> value);
        partial void OnConversationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PartnerCultureID
        {
            get
            {
                return _PartnerCultureID;
            }
            set
            {
                OnPartnerCultureIDChanging(value);
                ReportPropertyChanging("PartnerCultureID");
                _PartnerCultureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PartnerCultureID");
                OnPartnerCultureIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PartnerCultureID;
        partial void OnPartnerCultureIDChanging(Nullable<global::System.Int32> value);
        partial void OnPartnerCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__Conversat__Partn__0CBAE877", "CultureFiveDimension")]
        public CultureFiveDimension CultureFiveDimension
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "CultureFiveDimension").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "CultureFiveDimension").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CultureFiveDimension> CultureFiveDimensionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "CultureFiveDimension");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "CultureFiveDimension", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CultureAppModel", Name="CultureFiveDimension")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CultureFiveDimension : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CultureFiveDimension object.
        /// </summary>
        /// <param name="cultureID">Initial value of the CultureID property.</param>
        public static CultureFiveDimension CreateCultureFiveDimension(global::System.Int32 cultureID)
        {
            CultureFiveDimension cultureFiveDimension = new CultureFiveDimension();
            cultureFiveDimension.CultureID = cultureID;
            return cultureFiveDimension;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CultureID
        {
            get
            {
                return _CultureID;
            }
            set
            {
                if (_CultureID != value)
                {
                    OnCultureIDChanging(value);
                    ReportPropertyChanging("CultureID");
                    _CultureID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CultureID");
                    OnCultureIDChanged();
                }
            }
        }
        private global::System.Int32 _CultureID;
        partial void OnCultureIDChanging(global::System.Int32 value);
        partial void OnCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PDI
        {
            get
            {
                return _PDI;
            }
            set
            {
                OnPDIChanging(value);
                ReportPropertyChanging("PDI");
                _PDI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PDI");
                OnPDIChanged();
            }
        }
        private Nullable<global::System.Int32> _PDI;
        partial void OnPDIChanging(Nullable<global::System.Int32> value);
        partial void OnPDIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IDV
        {
            get
            {
                return _IDV;
            }
            set
            {
                OnIDVChanging(value);
                ReportPropertyChanging("IDV");
                _IDV = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IDV");
                OnIDVChanged();
            }
        }
        private Nullable<global::System.Int32> _IDV;
        partial void OnIDVChanging(Nullable<global::System.Int32> value);
        partial void OnIDVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MAS
        {
            get
            {
                return _MAS;
            }
            set
            {
                OnMASChanging(value);
                ReportPropertyChanging("MAS");
                _MAS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MAS");
                OnMASChanged();
            }
        }
        private Nullable<global::System.Int32> _MAS;
        partial void OnMASChanging(Nullable<global::System.Int32> value);
        partial void OnMASChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UAI
        {
            get
            {
                return _UAI;
            }
            set
            {
                OnUAIChanging(value);
                ReportPropertyChanging("UAI");
                _UAI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UAI");
                OnUAIChanged();
            }
        }
        private Nullable<global::System.Int32> _UAI;
        partial void OnUAIChanging(Nullable<global::System.Int32> value);
        partial void OnUAIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LTO
        {
            get
            {
                return _LTO;
            }
            set
            {
                OnLTOChanging(value);
                ReportPropertyChanging("LTO");
                _LTO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LTO");
                OnLTOChanged();
            }
        }
        private Nullable<global::System.Int32> _LTO;
        partial void OnLTOChanging(Nullable<global::System.Int32> value);
        partial void OnLTOChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__Conversat__Partn__0CBAE877", "ConversationCulture")]
        public EntityCollection<ConversationCulture> ConversationCultures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ConversationCulture>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "ConversationCulture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ConversationCulture>("CultureAppModel.FK__Conversat__Partn__0CBAE877", "ConversationCulture", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__DomainCul__Cultu__0DAF0CB0", "DomainCultureMapping")]
        public EntityCollection<DomainCultureMapping> DomainCultureMappings
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DomainCultureMapping>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "DomainCultureMapping");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DomainCultureMapping>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "DomainCultureMapping", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__Negotiati__Defau__0EA330E9", "NegotiationCulture")]
        public EntityCollection<NegotiationCulture> NegotiationCultures
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<NegotiationCulture>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "NegotiationCulture");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<NegotiationCulture>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "NegotiationCulture", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CultureAppModel", Name="DomainCultureMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DomainCultureMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DomainCultureMapping object.
        /// </summary>
        /// <param name="domainCultureMappingID">Initial value of the DomainCultureMappingID property.</param>
        public static DomainCultureMapping CreateDomainCultureMapping(global::System.Int32 domainCultureMappingID)
        {
            DomainCultureMapping domainCultureMapping = new DomainCultureMapping();
            domainCultureMapping.DomainCultureMappingID = domainCultureMappingID;
            return domainCultureMapping;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DomainCultureMappingID
        {
            get
            {
                return _DomainCultureMappingID;
            }
            set
            {
                if (_DomainCultureMappingID != value)
                {
                    OnDomainCultureMappingIDChanging(value);
                    ReportPropertyChanging("DomainCultureMappingID");
                    _DomainCultureMappingID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DomainCultureMappingID");
                    OnDomainCultureMappingIDChanged();
                }
            }
        }
        private global::System.Int32 _DomainCultureMappingID;
        partial void OnDomainCultureMappingIDChanging(global::System.Int32 value);
        partial void OnDomainCultureMappingIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DomainExt
        {
            get
            {
                return _DomainExt;
            }
            set
            {
                OnDomainExtChanging(value);
                ReportPropertyChanging("DomainExt");
                _DomainExt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DomainExt");
                OnDomainExtChanged();
            }
        }
        private global::System.String _DomainExt;
        partial void OnDomainExtChanging(global::System.String value);
        partial void OnDomainExtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CultureID
        {
            get
            {
                return _CultureID;
            }
            set
            {
                OnCultureIDChanging(value);
                ReportPropertyChanging("CultureID");
                _CultureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CultureID");
                OnCultureIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CultureID;
        partial void OnCultureIDChanging(Nullable<global::System.Int32> value);
        partial void OnCultureIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension")]
        public CultureFiveDimension CultureFiveDimension
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CultureFiveDimension> CultureFiveDimensionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CultureFiveDimension>("CultureAppModel.FK__DomainCul__Cultu__0DAF0CB0", "CultureFiveDimension", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CultureAppModel", Name="NegotiationCulture")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NegotiationCulture : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new NegotiationCulture object.
        /// </summary>
        /// <param name="negotiationCultureID">Initial value of the NegotiationCultureID property.</param>
        /// <param name="negotiationCultureType">Initial value of the NegotiationCultureType property.</param>
        public static NegotiationCulture CreateNegotiationCulture(global::System.Guid negotiationCultureID, global::System.Byte negotiationCultureType)
        {
            NegotiationCulture negotiationCulture = new NegotiationCulture();
            negotiationCulture.NegotiationCultureID = negotiationCultureID;
            negotiationCulture.NegotiationCultureType = negotiationCultureType;
            return negotiationCulture;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid NegotiationCultureID
        {
            get
            {
                return _NegotiationCultureID;
            }
            set
            {
                if (_NegotiationCultureID != value)
                {
                    OnNegotiationCultureIDChanging(value);
                    ReportPropertyChanging("NegotiationCultureID");
                    _NegotiationCultureID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NegotiationCultureID");
                    OnNegotiationCultureIDChanged();
                }
            }
        }
        private global::System.Guid _NegotiationCultureID;
        partial void OnNegotiationCultureIDChanging(global::System.Guid value);
        partial void OnNegotiationCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> NegotiationID
        {
            get
            {
                return _NegotiationID;
            }
            set
            {
                OnNegotiationIDChanging(value);
                ReportPropertyChanging("NegotiationID");
                _NegotiationID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationID");
                OnNegotiationIDChanged();
            }
        }
        private Nullable<global::System.Guid> _NegotiationID;
        partial void OnNegotiationIDChanging(Nullable<global::System.Guid> value);
        partial void OnNegotiationIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte NegotiationCultureType
        {
            get
            {
                return _NegotiationCultureType;
            }
            set
            {
                OnNegotiationCultureTypeChanging(value);
                ReportPropertyChanging("NegotiationCultureType");
                _NegotiationCultureType = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NegotiationCultureType");
                OnNegotiationCultureTypeChanged();
            }
        }
        private global::System.Byte _NegotiationCultureType;
        partial void OnNegotiationCultureTypeChanging(global::System.Byte value);
        partial void OnNegotiationCultureTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DefaultCultureID
        {
            get
            {
                return _DefaultCultureID;
            }
            set
            {
                OnDefaultCultureIDChanging(value);
                ReportPropertyChanging("DefaultCultureID");
                _DefaultCultureID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DefaultCultureID");
                OnDefaultCultureIDChanged();
            }
        }
        private Nullable<global::System.Int32> _DefaultCultureID;
        partial void OnDefaultCultureIDChanging(Nullable<global::System.Int32> value);
        partial void OnDefaultCultureIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private Nullable<global::System.Boolean> _Deleted;
        partial void OnDeletedChanging(Nullable<global::System.Boolean> value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> DeletedBy
        {
            get
            {
                return _DeletedBy;
            }
            set
            {
                OnDeletedByChanging(value);
                ReportPropertyChanging("DeletedBy");
                _DeletedBy = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedBy");
                OnDeletedByChanged();
            }
        }
        private Nullable<global::System.Guid> _DeletedBy;
        partial void OnDeletedByChanging(Nullable<global::System.Guid> value);
        partial void OnDeletedByChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedOn
        {
            get
            {
                return _DeletedOn;
            }
            set
            {
                OnDeletedOnChanging(value);
                ReportPropertyChanging("DeletedOn");
                _DeletedOn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedOn");
                OnDeletedOnChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedOn;
        partial void OnDeletedOnChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedOnChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CultureAppModel", "FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension")]
        public CultureFiveDimension CultureFiveDimension
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CultureFiveDimension> CultureFiveDimensionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CultureFiveDimension>("CultureAppModel.FK__Negotiati__Defau__0EA330E9", "CultureFiveDimension", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
