//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace citPOINT.CultureApp.ViewModel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("citPOINT.CultureApp.ViewModel.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IDV : Individualism..
        /// </summary>
        internal static string IDV_Description {
            get {
                return ResourceManager.GetString("IDV_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTO : Long-Term Orientation..
        /// </summary>
        internal static string LTO_Description {
            get {
                return ResourceManager.GetString("LTO_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAS : Masculinity..
        /// </summary>
        internal static string MAS_Description {
            get {
                return ResourceManager.GetString("MAS_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose partner culture..
        /// </summary>
        internal static string PartnerCultureRequired {
            get {
                return ResourceManager.GetString("PartnerCultureRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose partner culture if your choice &quot;Is Always&quot;..
        /// </summary>
        internal static string PartnerCultureRequiredIsAlways {
            get {
                return ResourceManager.GetString("PartnerCultureRequiredIsAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDI : Power Distance Index..
        /// </summary>
        internal static string PDI_Description {
            get {
                return ResourceManager.GetString("PDI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAI : Uncertainty Avoidance Index..
        /// </summary>
        internal static string UAI_Description {
            get {
                return ResourceManager.GetString("UAI_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose your culture..
        /// </summary>
        internal static string UserCultureRequired {
            get {
                return ResourceManager.GetString("UserCultureRequired", resourceCulture);
            }
        }
    }
}
